analyzer:
  en: prompt/argument/analyzer_en.txt
  zh: prompt/argument/analyzer_zh.txt
  ar: prompt/argument/analyzer_ar.txt
reviewer:
  en: prompt/argument/reviewer_en.txt
  zh: prompt/argument/reviewer_zh.txt
  ar: prompt/argument/reviewer_ar.txt
searcher:
  en: prompt/searcher.txt
  zh: prompt/searcher.txt
  ar: prompt/searcher.txt
system:
  en: prompt/argument/system_en.txt
  zh: prompt/argument/system_zh.txt
  ar: prompt/argument/system_ar.txt
task:
  en: prompt/argument/task_en.txt
  zh: prompt/argument/task_zh.txt
  ar: prompt/argument/task_ar.txt
writer:
  en: prompt/argument/writer_en.txt
  zh: prompt/argument/writer_zh.txt
  ar: prompt/argument/writer_ar.txt
