analyzer:
  en: prompt/rebuttal/analyzer_en.txt
  zh_neg: prompt/rebuttal/analyzer_zh_neg.txt
  zh_pos: prompt/rebuttal/analyzer_zh_pos.txt
  ar_neg: prompt/rebuttal/analyzer_ar_neg.txt
  ar_pos: prompt/rebuttal/analyzer_ar_pos.txt
reviewer:
  en: prompt/rebuttal/reviewer_en.txt
  zh_neg: prompt/rebuttal/reviewer_zh_neg.txt
  zh_pos: prompt/rebuttal/reviewer_zh_pos.txt
  ar_neg: prompt/rebuttal/reviewer_ar_neg.txt
  ar_pos: prompt/rebuttal/reviewer_ar_pos.txt

searcher:
  en: prompt/searcher_en.txt
  zh: prompt/searcher_zh.txt
  ar: prompt/searcher_ar.txt
system:
  en: prompt/rebuttal/system_en.txt
  zh: prompt/rebuttal/system_zh.txt
  ar: prompt/rebuttal/system_ar.txt
task:
  en: prompt/rebuttal/task_en.txt
  zh: prompt/rebuttal/task_zh.txt
  ar: prompt/rebuttal/task_ar.txt
writer:
  en: prompt/rebuttal/writer_en.txt
  zh_pos: prompt/rebuttal/writer_zh_pos.txt
  zh_neg: prompt/rebuttal/writer_zh_neg.txt
  ar_neg: prompt/rebuttal/writer_ar_neg.txt
  ar_pos: prompt/rebuttal/writer_ar_pos.txt
